### ISSUE TITLE
how did you convert the "Arcticons Thin Line Icons pack" to "d="

### ISSUE THREAD

**Issue by makuru-org** [tchartron/blow#12]
i want to add some custom vector for the website but i seem to get these files as
`<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 48 48"><defs><style>.a{fill:none;stroke:#000;stroke-linecap:round;stroke-linejoin:round;}</style></defs><circle class="a" cx="24" cy="24" r="9.44"/><circle class="a" cx="9.53" cy="24" r="5.03"/><circle class="a" cx="38.47" cy="24" r="5.03"/></svg>`
 not a data "d=" string, how did you do it?

**Comment by tchartron** [comment]
Hi and sorry for the (very) late answer, i don't now what you're using to create svg icons, i like to use [Heroicon](https://heroicons.com/) / [Heroicon (dev)](https://heroicons.dev/) / [Bootstrap](https://icons.getbootstrap.com/) i can just recomend using these to help you ..
