### ISSUE TITLE
Markdown numbering doesn't seem to be recognized.

### ISSUE THREAD

**Issue by akmijares** [tchartron/blow#16]
Hello,

It appears that markdown/website theme isn't recognizing the number format when you try to apply it.
It does seem to recognize all the other formats (code blocks, comments, etc.)

Markdown text:
![image](https://github.com/tchartron/blow/assets/33104169/de3d4f9e-4ee0-43ad-b754-096007aeffe1)
Rendered:
![image](https://github.com/tchartron/blow/assets/33104169/4f34571e-f391-408a-bbf8-4a23944ad30f)

Let me know if you have any questions/concerns.

**Comment by awinterstein** [comment]
This can be fixed, by extending the `main.css` file like in here: https://github.com/awinterstein/zola-theme-project-portfolio/commit/6801edcd0149b8816559bd7029c714dcb80b0820

I would create a pull-request here, but I do not have the environment to execute the old version of Tailwind CSS that is used in this repository. Hence, I am not able to create the output CSS file via Tailwind CSS. Feel free, to just use my code here as well.

**Comment by tjdwill** [comment]
> This can be fixed, by extending the `main.css` file like in here: [awinterstein/zola-theme-project-portfolio@6801edc](https://github.com/awinterstein/zola-theme-project-portfolio/commit/6801edcd0149b8816559bd7029c714dcb80b0820)
> 
> I would create a pull-request here, but I do not have the environment to execute the old version of Tailwind CSS that is used in this repository. Hence, I am not able to create the output CSS file via Tailwind CSS. Feel free, to just use my code here as well.

Hello, I'm new to Web Development in general and wanted to ask some clarifying questions about your reply.

Regarding `main.css` extension, I see in your link that there's one version that this theme defines (in `static/css/main.css` ?) and another that resides in the site directory (`src/css/main.css` ?). Why doesn't the existence of the file in the site directory override the one in the theme directory like a non-extending `index.html` would?

Also, is there a way to get nested bulleted lists and quotes to render? It currently doesn't do so for me, even with the proper Markdown.

**Comment by awinterstein** [comment]
The reason for the two `main.css` files is, that this theme uses [Tailwind CSS](https://tailwindcss.com/) for the design and CSS handling. In the `src/css/main.css` the configuration and CSS definition for Tailwind CSS is done. And then, Tailwind CSS needs to be executed to generate the `static/css/main.css`.

The Zola site then only uses the `static/css/main.css` file and does not even know about the input file `src/css/main.css`.

Regarding nested bullet points: That works with my proposed change as well.
![image](https://github.com/user-attachments/assets/80fe99bd-5a36-48f0-86ad-1a8b53721941)

It just seems that the margins would still need some adaptions to display a list in a nice way.

For quotes to render, I assume the corresponding style is just not defined in the `main.css` and would need to be added there.

**Comment by tjdwill** [comment]
Thank you for explaining that.

So just so I understand, your original comment proposes that we change `blow/src/css/main.css` such that your changes take effect, or are you recommending copying the linked `static/css/main.css` into our directories?

Or should we just replace `src/css/main.css` with the one you linked?

So far, the only way to see the changes you've posted was to directly copy your linked `static/css/main.css` into my `public/css/main.css`.

**Comment by awinterstein** [comment]
My suggestion would be to change the `blow/src/css/main.css` similar to what I did and then execute Tailwind CSS to generate the `static/css/main.css`. You cannot just copy the `static/css/main.css`, because it contains other changes as well, that should not necessarily be applied to this repository here.

The command would be like: `tailwindcss -i src/css/main.css -o static/css/main.css --minify`

I just have no idea how to run Tailwind CSS with the NodeJS infrastructure that is defined in this repository, because I am also not a web developer :smile: In my repository, I'm just using the Tailwind CSS CLI application. This application, however, is not available for the old version of Tailwind CSS that is defined in this repository here.

**Comment by tjdwill** [comment]
Gotcha. I'll try to study your project to learn a few things.  Thank you for your help.


@tchartron is there a way to get this fixed? Do you have a contribution process?

**Comment by awinterstein** [comment]
> Gotcha. I'll try to study your project to learn a few things. Thank you for your help.

You're welcome!

**Comment by tchartron** [comment]
Hey guys, i'm sorry i don't have much time to invest into maintaining this project as it should ...
@tjdwill if you want to push a fix for this issue you're very welcome to do so, i'll take the time to review the PR and merge it if everything is fine.
Migrating to Tailwind v3 would be great, if i have some time any time soon to investigate about this i'll do it 😉 
Thanks a lot for your contributions and you interest in this project !

**Comment by tjdwill** [comment]
> Hey guys, i'm sorry i don't have much time to invest into maintaining this project as it should ... @tjdwill if you want to push a fix for this issue you're very welcome to do so, i'll take the time to review the PR and merge it if everything is fine. Migrating to Tailwind v3 would be great, if i have some time any time soon to investigate about this i'll do it 😉 Thanks a lot for your contributions and you interest in this project !

No problem, I understand life gets busy! I've done my best to implement the changes with my limited experience in Request #22. Please let me know what you think, and thank you for the lovely theme.

**Comment by tchartron** [comment]
I just merged it ! Thanks a lot for your contribution @tjdwill  @awinterstein  👍🏼

**Comment by akmijares** [comment]
Hi! Yes I've been somewhat following this for the past day now, and yes I can confirm it's properly working now. Thanks guys!

**Comment by tchartron** [comment]
Awesome, thanks for confirmation and thanks again for the work guys 👍🏼 🚀

**Comment by tjdwill** [comment]
Happy to help; thank you for being so responsive!
