### ISSUE TITLE
Trying to change the colors of the theme

### ISSUE THREAD

**Issue by nbaronariera** [tchartron/blow#23]
Hi. I'm working on the theme. I'm not sure if I've understood how theme colors work. How do I change them? I've assumed I need to edit the css in the static folder but to no avail. Is there an easier way that I'm not seeing? If not, when I get there I'll probably make some changes and try to push it.

**Comment by tchartron** [comment]
Hey, sorry for the late answer ..

You can change the theme css rules inthe `/src/css/main.css` file.
The files in `static` are not meant to be changed, they are "built" by the npm scripts.
Hope that helps !
