### ISSUE TITLE
How to customize the template file on `v1.1.0` ?

### ISSUE THREAD

**Issue by TD-Sky** [tchartron/blow#6]
I want to create a page to show my friends' blog links and this page will be navigated by navbar.

Specifically, this page locates at `/friends`. Its content is written at `/content/friends/_index.md`.

So the template of the page is similar to `section` but it doesn't need most metadata.

I completely copy `section.html` to `friends.html`. However, Zola only rendered `config.title`, the content is empty.

Here are the references I studied, they come from another theme:
- template:  [links.html](https://github.com/longfangsong/anatole-zola/blob/main/templates/links.html)
- content: [_index.md](https://github.com/longfangsong/anatole-zola/blob/main/content/links/_index.md)

I would appreciate if you can help me.

**Comment by tchartron** [comment]
Hi,

I would like to help you but i don't understand what you're trying to achieve.

I think this is more a Zola related question, maybe you're trying to extend the theme ? (https://www.getzola.org/documentation/themes/extending-a-theme/)

`section.html`and `page.html` are Zola specific templates see : https://www.getzola.org/documentation/templates/pages-sections/

So you should be creating the content of you friends page into content like `/content/friends/list.md` with this maybe as metadata : 
```
+++ title = "Friends" description = "Friend list" template = "section.html" page_template = "friends.html" sort_by = "date" paginate_by = 5 +++
```

Something like this, hope this helps 😃

**Comment by TD-Sky** [comment]
Your advice is very useful!

I did it through following steps:

1. Create `content/content/friends.md` ;

2. Write the metadata as a general page. However, there must be `path = "/friends"` ;

3. Customize its style with `template = "friends.html"`. `friends.html` should be like `page.html` instead of `section.html`.

---

There is one more question: it seems that **Blow** doesn't render bullet list. Why?

**Comment by tchartron** [comment]
I'm happy i was able to help you ! 😃

Blow uses Tailwindcss as it's css framework and Tailwind unstyles many default components like html lists, see this link for more informations : https://tailwindcss.com/docs/preflight#lists-are-unstyled

So this is perfectly normal, but still you can use explicit css classes to style your lists : https://tailwindcss.com/docs/list-style-type

Have a nice day !
