### ISSUE TITLE
Add LICENSE file.

### ISSUE THREAD

**Issue by VV0JC13CH** [tchartron/blow#9]
Hi. Please add MIT License file. Currently the only source of truth about license type is: 
https://www.getzola.org/themes/blow/

I used "selection of language", "sidebar" and "deployment pipeline" from this repository in my theme and I want to include proper information in README and LICENSE to be precise about author and source of these pieces of code.

**Comment by VV0JC13CH** [comment]
Proposed PR: https://github.com/tchartron/blow/pull/10

**Comment by tchartron** [comment]
I'm going to merge this, thank you for adding License and thank you for being so careful about the pieces of code you use and how it's owner would want to share it, that is great respect 👍🏼
